name: AutoRP
version: '${version}'
main: xyz.irodev.autorp.AutoRP
api-version: 1.19
commands:
  rpupdate:
    permission: command.rpupdate

permissions:
  command.rpupdate:
    default: op

libraries:
  - at.favre.lib:bytes:1.5.0